--- #YAML:1.0
name:               Spreadsheet-ParseExcel
version:            0.59
abstract:           Read information from an Excel file.
author:
    - John McNamara (jmcnamara@cpan.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::File:           0
    IO::Scalar:         0
    OLE::Storage_Lite:  0.19
    Scalar::Util:       0
    perl:               5.008
    Crypt::RC4:         0
    Digest::Perl::MD5:  0
resources:
    MailingList:  http://groups.google.com/group/spreadsheet-parseexcel
    repository:   http://github.com/jmcnamara/spreadsheet-parseexcel
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
